ignore_merge_commits = false
tag_prefix = "v"

[commit_types]
chore = { changelog_title = "Chore", omit_from_changelog = true }
ci = { changelog_title = "CI", omit_from_changelog = true }
docs = { changelog_title = "Docs", omit_from_changelog = true }
coc = { changelog_title = "Coc.nvim", omit_from_changelog = true }
dotfile = { changelog_title = "Dotfile", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

