ignore_merge_commits = false
tag_prefix = "v"

[commit_types]
chore = { changelog_title = "Chore", omit_from_changelog = true }
ci = { changelog_title = "CI", omit_from_changelog = true }
docs = { changelog_title = "Docs", omit_from_changelog = true }
enhance = { changelog_title = "Enhancement", omit_from_changelog = false }

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

