CompileFlags:
  Add: [-Wall]

Diagnostics:
  # Still invalid for system header
  UnusedIncludes: Strict
  # Valid for system header
  MissingIncludes: Strict
  ClangTidy:
    Add:
      - modernize*
      - clang-analyzer-*
      - llvm-*
      - google-*
      - cppcoreguidelines-*
      # Warning for short variables like `a`
      # - readability-*
    # auto foo() -> int;
    Remove:
      - cppcoreguidelines-pro-type-vararg
      - cppcoreguidelines-avoid-magic-numbers
      - modernize-use-trailing-return-type

InlayHints:
  Parameters: true
  DeducedTypes: true

