[foxmail]
backend = "imap"
email = "jiangyinzuo@foxmail.com"
default = false
display-name = "Yinzuo Jiang"
imap-host = "imap.qq.com"
imap-port = 993
imap-ssl = true
imap-login = "jiangyinzuo@foxmail.com"
imap-auth = "passwd"
sender = "smtp"
smtp-host = "smtp.qq.com"
smtp-port = 465
smtp-ssl = true
smtp-login = "jiangyinzuo@foxmail.com"
smtp-auth = "passwd"

[foxmail.pgp]
backend = "none"

[ict]
backend = "imap"
email = "jiangyinzuo22s@ict.ac.cn"
default = false
display-name = "Yinzuo Jiang"
imap-host = "mail.cstnet.cn"
imap-port = 993
imap-ssl = true
imap-login = "jiangyinzuo22s@ict.ac.cn"
imap-auth = "passwd"
sender = "smtp"
smtp-host = "mail.cstnet.cn"
smtp-port = 465
smtp-ssl = true
smtp-login = "jiangyinzuo22s@ict.ac.cn"
smtp-auth = "passwd"

[ict.pgp]
backend = "none"

[ucas]
backend = "imap"
email = "jiangyinzuo22@mails.ucas.ac.cn"
default = true
display-name = "Yinzuo Jiang"
imap-host = "mail.cstnet.cn"
imap-port = 993
imap-ssl = true
imap-login = "jiangyinzuo22@mails.ucas.ac.cn"
imap-auth = "passwd"
sender = "smtp"
smtp-host = "mail.cstnet.cn"
smtp-port = 465
smtp-ssl = true
smtp-login = "jiangyinzuo22@mails.ucas.ac.cn"
smtp-auth = "passwd"

[ucas.pgp]
backend = "none"
